apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-with-hook
spec:
  project: default
  source:
    repoURL: https://github.com/alexmt/argocd-example-apps
    targetRevision: HEAD
    path: 'app-hook'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hook
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  project: default
  source:
    repoURL: file:///tmp/app-hook
    targetRevision: HEAD
    path: 'app-hook'
    directory:
      include: 'cm.yaml'
  destination:
    name: akp-001-dev-usw2
    namespace: default