apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-hooks
spec:
  destination:
    namespace: helm-hooks
    name: minikube
  project: default
  source:
    path: helm-hooks
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

