apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
spec:
  destination:
    namespace: sync-waves
    name: minikube
  project: default
  source:
    path: sync-waves
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
