apiVersion: v1
kind: Pod
metadata:
  name: post-delete-hook
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  containers:
  - name: post-delete-hook
    image: busybox
    restartPolicy: Never
    command: ["/bin/sh", "-c", "sleep 5 && echo hello from the post-delete-hook pod"]
