apiVersion: v1
kind: Pod
metadata:
  name: post-delete-hook
  annotations:
    argocd.argoproj.io/hook: PostDelete
spec:
  containers:
  - name: post-delete-hook
    image: busybox
    command: ["/bin/sh", "-c", "echo hello from the post-delete-hook pod"]
