apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: '5146/app1'
    repoURL: https://github.com/alexmt/argocd-example-apps
    targetRevision: '5146'
  syncPolicy:
    automated: {}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: '5146/app2'
    repoURL: https://github.com/alexmt/argocd-example-apps
    targetRevision: '5146'
  syncPolicy:
    automated: {}
